export const wallpaperMaterials = [
  {
    id: 1,
    name: "FabricFresco-Fabric Back",
    code: "PP01",
    price: 45,
    rating: 4.8,
    category: "Premium",
    description: "Smooth matte finish ideal for residential applications with excellent print quality.",
    features: ["Water", "Eco"],
    image: "/material/1.jpg",
    badge: "premium",
    specs: [
      { key: "Thickness", value: "180 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "5-10 years" },
      { key: "Installation", value: "Professional Required" },
    ],
  },
  {
    id: 2,
    name: "FabricFresco-Fabric Back (Foil)",
    code: "PP01",
    price: 65,
    rating: 4.7,
    category: "Commercial",
    description: "Heavy-duty vinyl designed for commercial spaces with maximum durability.",
    features: ["Water", "Fire"],
    image: "/material/2.jpg",
    badge: "commercial",
    specs: [
      { key: "Thickness", value: "220 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "10-15 years" },
      { key: "Fire Resistance", value: "Yes" },
      { key: "Installation", value: "Professional Required" },
      { key: "Foil Colors Available", value: "Gold, Silver, Bronze" },
    ],
  },
  {
    id: 3,
    name: "FabricFresco-Fabric Back (Embossed)",
    code: "PP01",
    price: 35,
    rating: 4.3,
    category: "Eco",
    description: "Sustainable paper-based wallpaper made from recycled materials.",
    features: ["Eco"],
    image: "/material/3.jpg",
    badge: "eco",
    specs: [
      { key: "Thickness", value: "150 GSM" },
      { key: "Width", value: "Up to 100 inches" },
      { key: "Durability", value: "3-5 years" },
      { key: "Eco Certification", value: "FSC Certified" },
      { key: "Installation", value: "Professional Recommended" },
    ],
  },
  {
    id: 4,
    name: "Nonwoven Feather",
    code: "PP05",
    price: 85,
    rating: 4.9,
    category: "Premium",
    description: "High-end vinyl with superior durability and premium finish. Perfect for high-traffic areas.",
    features: ["Water", "Fire"],
    image: "/material/4.jpg",
    badge: "premium",
    specs: [
      { key: "Thickness", value: "250 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "12-15 years" },
      { key: "Scratch Resistance", value: "Yes" },
      { key: "Installation", value: "Professional Required" },
    ],
  },
  {
    id: 5,
    name: "Paint Brush-Fabric Back",
    code: "PP12",
    price: 55,
    rating: 4.6,
    category: "Standard",
    description: "Canvas texture wallpaper perfect for creating artistic wall finishes.",
    features: ["Eco", "Scratch"],
    image: "/material/5.jpg",
    badge: "standard",
    specs: [
      { key: "Thickness", value: "200 GSM" },
      { key: "Width", value: "Up to 110 inches" },
      { key: "Durability", value: "6-8 years" },
      { key: "Texture", value: "Canvas Finish" },
      { key: "Installation", value: "DIY / Professional" },
    ],
  },
  {
    id: 6,
    name: "Glitter-Canvas",
    code: "PP14",
    price: 95,
    rating: 4.9,
    category: "Luxury",
    description: "Premium metallic finish wallpaper with stunning reflective properties.",
    features: ["Water", "UV"],
    image: "/material/6.jpg",
    badge: "luxury",
    specs: [
      { key: "Thickness", value: "210 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "8-12 years" },
      { key: "UV Resistance", value: "Yes" },
      { key: "Installation", value: "Professional Required" },
    ],
  },
  {
    id: 7,
    name: "Ridges Texture - Nonwoven",
    code: "PP15",
    price: 75,
    rating: 4.5,
    category: "Contemporary",
    description: "Modern geometric patterns with vibrant colors for contemporary interiors.",
    features: ["Eco", "Washable"],
    image: "/material/7.jpg",
    badge: "contemporary",
    specs: [
      { key: "Thickness", value: "180 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "5-10 years" },
      { key: "Washable", value: "Yes" },
      { key: "Installation", value: "DIY / Professional" },
    ],
  },
  {
    id: 8,
    name: "Ridges Texture - Nonwoven",
    code: "PP15",
    price: 60,
    rating: 4.4,
    category: "Standard",
    description: "Vinyl wallpaper with a textured finish for added depth and character.",
    features: ["Water", "Scratch"],
    image: "/material/8.jpg",
    badge: "standard",
    specs: [
      { key: "Thickness", value: "200 GSM" },
      { key: "Width", value: "Up to 110 inches" },
      { key: "Durability", value: "6-8 years" },
      { key: "Texture", value: "Textured Finish" },
      { key: "Installation", value: "DIY / Professional" },
    ],
  },
  {
    id: 9,
    name: "Nonwoven Lined",
    code: "PP02",
    price: 75,
    rating: 4.5,
    category: "Contemporary",
    description: "Modern geometric patterns with vibrant colors for contemporary interiors.",
    features: ["Eco", "Washable"],
    image: "/material/9.jpg",
    badge: "contemporary",
    specs: [
      { key: "Thickness", value: "180 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "5-10 years" },
      { key: "Washable", value: "Yes" },
      { key: "Installation", value: "DIY / Professional" },
    ],
  },
  {
    id: 10,
    name: "Texture Canvas",
    code: "PP08",
    price: 85,
    rating: 4.8,
    category: "Luxury",
    description: "Premium textured wallpaper with a luxurious feel and appearance.",
    features: ["Water", "UV"],
    image: "/material/10.jpg",
    badge: "luxury",
    specs: [
      { key: "Thickness", value: "220 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "8-12 years" },
      { key: "UV Resistance", value: "Yes" },
      { key: "Installation", value: "Professional Required" },
    ],
  },
  {
    id: 11,
    name: "Texture Hairlines",
    code: "PP04",
    price: 90,
    rating: 4.9,
    category: "Premium",
    description: "High-end vinyl with superior durability and premium finish. Perfect for high-traffic areas.",
    features: ["Water", "Fire"],
    image: "/material/11.jpg",
    badge: "premium",
    specs: [
      { key: "Thickness", value: "250 GSM" },
      { key: "Width", value: "Up to 120 inches" },
      { key: "Durability", value: "12-15 years" },
      { key: "Scratch Resistance", value: "Yes" },
      { key: "Installation", value: "Professional Required" },
    ],
  },



]

export const rollerBlindsMaterials = [
  {
    id: 1,
    name: "Blackout Roller",
    code: "RB-001",
    price: 70,
    rating: 4.7,
    category: "Blackout",
    description: "100% light-blocking fabric ideal for bedrooms and offices.",
    features: ["UV Protection", "Privacy"],
    image: "/roller/blackout.jpg",
    badge: "popular",
    specs: [
      { key: "Opacity", value: "100% Blackout" },
      { key: "Width", value: "Up to 300 cm" },
      { key: "Control", value: "Chain / Motorized" },
      { key: "Durability", value: "7-10 years" },
    ],
  },
  {
    id: 2,
    name: "Sunscreen Roller",
    code: "RB-002",
    price: 55,
    rating: 4.5,
    category: "Sunscreen",
    description: "Light filtering with UV protection and outside visibility.",
    features: ["UV Protection", "Daylight View"],
    image: "/roller/sunscreen.jpg",
    badge: "eco",
    specs: [
      { key: "Opacity", value: "5-10% Open" },
      { key: "Width", value: "Up to 280 cm" },
      { key: "Control", value: "Chain / Motorized" },
      { key: "Durability", value: "5-8 years" },
    ],
  },
]

export const romanBlindsMaterials = [
  {
    id: 1,
    name: "Cotton Roman",
    code: "ROM-001",
    price: 65,
    rating: 4.6,
    category: "Fabric",
    description: "Elegant folds with premium cotton fabric.",
    features: ["Soft Look", "Washable"],
    image: "/roman/cotton.jpg",
    badge: "standard",
    specs: [
      { key: "Fabric", value: "Cotton" },
      { key: "Opacity", value: "Semi Blackout" },
      { key: "Control", value: "Cord / Chain" },
      { key: "Durability", value: "5-7 years" },
    ],
  },
  {
    id: 2,
    name: "Linen Roman",
    code: "ROM-002",
    price: 80,
    rating: 4.8,
    category: "Luxury",
    description: "Linen fabric roman blind with natural texture.",
    features: ["Eco", "Premium Texture"],
    image: "/roman/linen.jpg",
    badge: "luxury",
    specs: [
      { key: "Fabric", value: "Linen" },
      { key: "Opacity", value: "Light Filtering" },
      { key: "Control", value: "Cord / Chain" },
      { key: "Durability", value: "6-9 years" },
    ],
  },
]

export const zebraBlindsMaterials = [
  {
    id: 1,
    name: "Standard Zebra",
    code: "ZB-001",
    price: 75,
    rating: 4.7,
    category: "Dual Shade",
    description: "Alternate sheer and opaque fabric for day-night use.",
    features: ["Light Control", "Privacy"],
    image: "/zebra/standard.jpg",
    badge: "best-seller",
    specs: [
      { key: "Fabric", value: "Polyester" },
      { key: "Control", value: "Chain / Motorized" },
      { key: "Light Control", value: "Adjustable Sheer & Opaque" },
      { key: "Durability", value: "6-8 years" },
    ],
  },
  {
    id: 2,
    name: "Premium Zebra",
    code: "ZB-002",
    price: 95,
    rating: 4.9,
    category: "Luxury",
    description: "Premium fabric zebra blind with smoother transitions.",
    features: ["UV Protection", "Luxury Finish"],
    image: "/zebra/premium.jpg",
    badge: "luxury",
    specs: [
      { key: "Fabric", value: "Polyester Blend" },
      { key: "Control", value: "Motorized Preferred" },
      { key: "Light Control", value: "Day-Night Adjustable" },
      { key: "Durability", value: "8-10 years" },
    ],
  },
]

export const verticalBlindsMaterials = [
  {
    id: 1,
    name: "PVC Vertical",
    code: "VB-001",
    price: 50,
    rating: 4.5,
    category: "PVC",
    description: "Durable PVC slats ideal for offices and schools.",
    features: ["Waterproof", "Budget Friendly"],
    image: "/vertical/pvc.jpg",
    badge: "standard",
    specs: [
      { key: "Slat Width", value: "89mm / 127mm" },
      { key: "Control", value: "Cord / Wand" },
      { key: "Durability", value: "6-8 years" },
      { key: "Opacity", value: "Blackout / Semi" },
    ],
  },
  {
    id: 2,
    name: "Fabric Vertical",
    code: "VB-002",
    price: 65,
    rating: 4.6,
    category: "Fabric",
    description: "Soft fabric slats for elegant interiors.",
    features: ["Soft Look", "Washable"],
    image: "/vertical/fabric.jpg",
    badge: "premium",
    specs: [
      { key: "Slat Width", value: "89mm / 127mm" },
      { key: "Control", value: "Cord / Wand" },
      { key: "Durability", value: "5-7 years" },
      { key: "Opacity", value: "Semi Blackout" },
    ],
  },
]
